# Generated by Django 2.1.8 on 2019-12-05 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientfile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='note',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='备注'),
        ),
    ]
