# Generated by Django 2.1.13 on 2019-12-11 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientfile', '0002_client_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['rd', 'rm', 'dsm', 'rsp', 'hospital', 'dept', 'name'], 'verbose_name': '客户档案', 'verbose_name_plural': '客户档案'},
        ),
        migrations.RemoveField(
            model_name='client',
            name='monthly_prescription',
        ),
        migrations.RemoveField(
            model_name='client',
            name='phone',
        ),
        migrations.AlterField(
            model_name='client',
            name='title',
            field=models.CharField(choices=[('主任医师', '主任医师'), ('副主任医师', '副主任医师'), ('主治医师', '主治医师'), ('住院医师', '住院医师')], max_length=10, verbose_name='职称'),
        ),
    ]
