# Generated by Django 2.1.13 on 2020-03-11 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientfile', '0003_auto_20191211_1459'),
    ]
