# Generated by Django 3.0 on 2020-03-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientfile', '0005_auto_20200324_1058'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='client',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(condition=models.Q(is_deleted=False), fields=('rsp', 'hospital', 'dept', 'name'), name='unique_if_not_deleted'),
        ),
    ]
