# Generated by Django 2.1.8 on 2019-10-28 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xltid', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('rsp', models.CharField(max_length=10)),
                ('dsm', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateTimeField(verbose_name='记录时间')),
                ('pub_date', models.DateTimeField(verbose_name='上传时间')),
                ('note_text', models.CharField(max_length=200)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheets.Hospital')),
            ],
        ),
    ]
