# Generated by Django 2.1.8 on 2019-10-28 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='project_expense1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='record',
            name='project_expense2',
            field=models.IntegerField(default=0),
        ),
    ]
