# Generated by Django 2.1.8 on 2019-10-28 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0002_auto_20191028_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='dsm',
            field=models.CharField(max_length=10, verbose_name='所属区域'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='name',
            field=models.CharField(max_length=30, verbose_name='医院名称'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='rsp',
            field=models.CharField(max_length=10, verbose_name='负责代表'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='xltid',
            field=models.CharField(max_length=10, verbose_name='信立泰医院id'),
        ),
        migrations.AlterField(
            model_name='record',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheets.Hospital', verbose_name='医院'),
        ),
        migrations.AlterField(
            model_name='record',
            name='note_text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='record',
            name='project_expense1',
            field=models.IntegerField(default=0, verbose_name='PMS盒数'),
        ),
        migrations.AlterField(
            model_name='record',
            name='project_expense2',
            field=models.IntegerField(default=0, verbose_name='True盒数'),
        ),
        migrations.AlterField(
            model_name='record',
            name='pub_date',
            field=models.DateTimeField(auto_now=True, verbose_name='上传日期'),
        ),
        migrations.AlterField(
            model_name='record',
            name='record_date',
            field=models.DateField(verbose_name='记录日期'),
        ),
    ]
