# Generated by Django 2.1.8 on 2019-10-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0003_auto_20191028_1220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hospital',
            options={'ordering': ['name', 'rsp', 'dsm']},
        ),
        migrations.RenameField(
            model_name='record',
            old_name='project_expense1',
            new_name='project1_volume',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='project_expense2',
            new_name='project2_volume',
        ),
        migrations.AlterField(
            model_name='record',
            name='note_text',
            field=models.CharField(blank=True, max_length=200, verbose_name='备注'),
        ),
    ]
