# Generated by Django 2.1.8 on 2019-10-29 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0004_auto_20191028_1740'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['hospital__name', 'hospital__rsp', 'record_date']},
        ),
        migrations.AddField(
            model_name='record',
            name='cp_expense',
            field=models.IntegerField(default=0, verbose_name='CP实际报销金额'),
        ),
        migrations.AddField(
            model_name='record',
            name='hospital_sales',
            field=models.IntegerField(default=0, verbose_name='医院进货盒数'),
        ),
        migrations.AddField(
            model_name='record',
            name='round_table_expense',
            field=models.IntegerField(default=0, verbose_name='科室会和点评会报销金额'),
        ),
        migrations.AddField(
            model_name='record',
            name='round_table_times',
            field=models.IntegerField(default=0, verbose_name='科室会次数'),
        ),
    ]
