# Generated by Django 2.1.8 on 2019-10-29 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0005_auto_20191029_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='note_text',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='备注'),
        ),
    ]
