# Generated by Django 2.1.8 on 2019-10-29 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0006_auto_20191029_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='record_date',
            field=models.DateTimeField(verbose_name='记录日期'),
        ),
    ]
