# Generated by Django 2.1.8 on 2019-11-19 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0008_jobposition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='姓名')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='sheets.Staff', verbose_name='上级人员')),
            ],
            options={
                'verbose_name': '人员',
                'verbose_name_plural': '人员',
                'db_table': 'staff',
            },
        ),
        migrations.RemoveField(
            model_name='jobposition',
            name='parent',
        ),
        migrations.DeleteModel(
            name='JobPosition',
        ),
    ]
