# Generated by Django 2.1.8 on 2019-11-19 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0009_auto_20191119_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='dsm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sheets.Staff', verbose_name='所属大区'),
        ),
        migrations.AlterField(
            model_name='record',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sheets.Hospital', verbose_name='医院'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='name',
            field=models.CharField(max_length=10, unique=True, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='sheets.Staff', verbose_name='上级人员'),
        ),
    ]
