# Generated by Django 2.1.8 on 2019-11-19 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0010_auto_20191119_1746'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={},
        ),
    ]
