# Generated by Django 2.1.13 on 2019-12-11 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0011_auto_20191119_1749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hospital',
            options={'ordering': ['name', 'rsp', 'dsm'], 'verbose_name': '医院-代表', 'verbose_name_plural': '医院-代表'},
        ),
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['hospital__name', 'hospital__rsp', 'record_date'], 'verbose_name': '费用记录', 'verbose_name_plural': '费用记录'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': '员工', 'verbose_name_plural': '团队架构'},
        ),
        migrations.AlterField(
            model_name='staff',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='staff',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='staff',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
